# Generated by Django 3.2 on 2021-07-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Contenu',
        ),
        migrations.AlterModelOptions(
            name='contenu',
            options={'verbose_name': 'contenu'},
        ),
    ]
